name: CI

on:
  push:
    branches:
      - classic
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 100

      - name: Create Package
        uses: QartemisT/packager@master
        with:
          args: -g bcc -n "DBM-{project-version}{classic}"
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
